# Generated by Django 3.1 on 2020-09-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='seed',
            field=models.BigIntegerField(),
        ),
    ]
